package com.gloriane.ecommerceappdemo.entity;

import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true) // Only included fields participate in equals/hashCode (safe for JPA)
@ToString(onlyExplicitlyIncluded = true) // Only included fields appear in toString (prevents recursion)

@Entity // Marks this class as a JPA entity
@Table(name = "addresses")  // Maps entity to "addresses" table
public class Address {

    @Id
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY) // Auto-generated by DB
    @EqualsAndHashCode.Include // Use id for equality when available
    @ToString.Include // Show id in toString
    private Long id; // Use id for equality when available

    @Column(nullable = false, length = 200)
    @ToString.Include
    private String street;

    @Column(nullable = false, length = 100)
    @ToString.Include
    private String city;

    @Column(nullable = false, length = 20)
    @ToString.Include
    private String zipCode;
}

